import { RootProvider } from 'fumadocs-ui/provider'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import { ReactNode } from 'react'

import { cn } from '@/lib/utils'
import '@/styles/globals.css'

export const metadata: Metadata = {
	title: 'NestJS Yookassa by TeaCoder',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='ru' suppressHydrationWarning>
			<body className={cn(GeistSans.variable)}>
				<RootProvider
					i18n={{
						locale: 'ru',
						translations: {
							search: 'Поиск',
							searchNoResult: 'Нечего не найдено',
							toc: 'На этой странице'
						}
					}}
				>
					{children}
				</RootProvider>
			</body>
		</html>
	)
}
